spring:
  profiles:
    active:
    - dev
---
server:
  port: 8001
spring:
  profiles: dev
  application:
    name: microservicecloud-config
eureka:
  instance:
    instance-id: microservicecloud-provider-dept-8001d
    prefer-ip-address: true                                #显示路径可以显示IP地址
  client:
    service-url:
      defaultZone: http://eureka1.com:7001/eureka/  
---
server:
  port: 8006
spring:
  profiles: test
  application:
    name: microservicecloud-config
eureka:
  instance:
    instance-id: microservicecloud-provider-dept-8001d
    prefer-ip-address: true                                #显示路径可以显示IP地址
  client:
    service-url:
      defaultZone: http://eureka1.com:7001/eureka/